/** AsyncStorage keys for Settings + AI client. */
export const STORAGE_USER_OPENROUTER_KEY = 'USER_OPENROUTER_API_KEY';
export const STORAGE_NOTIFICATIONS_ENABLED = 'SETTINGS_NOTIFICATIONS_ENABLED';
export const STORAGE_DARK_MODE = 'SETTINGS_DARK_MODE';
